# Generated by Django 4.2.4 on 2023-08-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_mqtt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uart',
            name='parity',
            field=models.CharField(choices=[('none', 'None'), ('odd', 'Odd'), ('even', 'Even')], max_length=10),
        ),
    ]
