# Generated by Django 4.2.4 on 2023-08-16 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buttonID', models.IntegerField(unique=True)),
                ('buttonName', models.CharField(max_length=20)),
                ('buttonColorName', models.CharField(max_length=20)),
                ('buttonColor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicatorID', models.IntegerField(unique=True)),
                ('indicatorpin', models.IntegerField(unique=True)),
                ('indicatorColor', models.IntegerField()),
                ('indicatorColorName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemID', models.IntegerField(unique=True)),
                ('problemName', models.CharField(max_length=30)),
                ('problemDescription', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField(unique=True)),
                ('acknowledgeUser', models.ManyToManyField(related_name='ackuser', to=settings.AUTH_USER_MODEL)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.button')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.indicator')),
                ('notifyUser', models.ManyToManyField(related_name='notiuser', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.problemcode')),
            ],
        ),
    ]
