# Generated by Django 4.2.4 on 2023-08-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicatorColor',
            field=models.CharField(max_length=7),
        ),
    ]
