# Generated by Django 4.2.4 on 2023-08-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_indicator_indicatorcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcode',
            name='problemID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
