# Generated by Django 4.2.4 on 2023-08-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_problemcode_problemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='buttonID',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
