# Generated by Django 4.2.4 on 2023-08-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_button_buttoncolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(max_length=15, unique=True)),
                ('events', models.ManyToManyField(related_name='eventGroup', to='events.event')),
            ],
        ),
    ]
