# Generated by Django 4.2.4 on 2023-08-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicatorID',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
