# Generated by Django 4.2.4 on 2023-08-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_indicator_indicatorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventID',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
