# Generated by Django 4.2.4 on 2023-08-26 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_alter_event_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='acknowledgeUser',
            field=models.ManyToManyField(blank=True, null=True, related_name='ackuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='notifyUser',
            field=models.ManyToManyField(blank=True, null=True, related_name='notiuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
