# Generated by Django 4.2.4 on 2023-08-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_acknowledgeuser_alter_event_notifyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='events.button'),
        ),
        migrations.AlterField(
            model_name='event',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='events.indicator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='events.problemcode'),
        ),
    ]
