# Generated by Django 4.2.4 on 2023-08-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_button_alter_event_indicator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.button'),
        ),
        migrations.AlterField(
            model_name='event',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.indicator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.problemcode'),
        ),
    ]
