# Generated by Django 4.2.4 on 2023-09-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_button_alter_event_indicator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='events',
        ),
    ]
