# Generated by Django 4.2.4 on 2023-09-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_eventgroup_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemcode',
            old_name='problemID',
            new_name='problemCode',
        ),
    ]
