# Generated by Django 4.2.4 on 2023-10-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_rename_problemid_problemcode_problemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='groupName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
