# Generated by Django 4.2.4 on 2023-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventgroup_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemcode',
            name='problemType',
            field=models.CharField(blank=True, choices=[('ISSUE', 'issue'), ('ACKNOWLEDGE', 'acknowledge'), ('FINE', 'fine')], max_length=15),
        ),
    ]
