# Generated by Django 4.2.4 on 2023-12-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_rfid_rfid_alter_unregistereddevice_deviceid'),
        ('events', '0018_problemcode_problemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='machines',
            field=models.ManyToManyField(related_name='MachinesList', to='devices.machine'),
        ),
    ]
