# Generated by Django 4.2.4 on 2023-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_rfid_rfid_alter_unregistereddevice_deviceid'),
        ('events', '0019_eventgroup_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='machines',
            field=models.ManyToManyField(related_name='machinesList', to='devices.machine'),
        ),
    ]
