# Generated by Django 4.2.4 on 2023-12-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_button_buttondo_button_buttonmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='buttonMode',
            field=models.CharField(choices=[('auto', 'AUTO'), ('manual', 'MANUAL')], default='auto', max_length=10),
        ),
    ]
