# Generated by Django 4.2.4 on 2023-12-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_button_buttonmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='buttonMode',
            field=models.CharField(choices=[('auto', 'AUTO'), ('manual', 'MANUAL'), ('auto+manual', 'AUTO+MANUAL')], default='auto', max_length=15),
        ),
    ]
