# Generated by Django 4.2.4 on 2023-08-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField(unique=True)),
                ('model', models.CharField(max_length=10)),
                ('hardwareVersion', models.CharField(max_length=10)),
                ('softwareVersion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('manufacture', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=10)),
                ('line', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/machineimages')),
                ('HMIDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.hmi')),
            ],
        ),
    ]
