# Generated by Django 4.2.4 on 2023-08-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmi',
            name='deviceID',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineID',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
