# Generated by Django 4.2.4 on 2023-08-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_hmi_deviceid_alter_machine_machineid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/machineimages'),
        ),
    ]
