# Generated by Django 4.2.4 on 2023-10-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_rename_hmi_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='HMIDevice',
            new_name='device',
        ),
    ]
