# Generated by Django 4.2.4 on 2023-10-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_rename_hmidevice_machine_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnRegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.UUIDField()),
                ('deviceID', models.CharField(max_length=15, unique=True)),
                ('model', models.CharField(max_length=10)),
                ('hardwareVersion', models.CharField(max_length=10)),
                ('softwareVersion', models.CharField(max_length=10)),
                ('devicePassword', models.CharField(max_length=20)),
                ('OTP', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
