# Generated by Django 4.2.4 on 2023-10-16 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_unregistereddevice_hardwareversion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.RemoveField(
            model_name='token',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AddField(
            model_name='token',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='key',
            field=models.CharField(default=123456789012345678, max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='deviceID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='devices.device', verbose_name='Device'),
        ),
    ]
