# Generated by Django 4.2.4 on 2023-10-17 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_token_options_remove_token_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(default=234, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='deviceID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deviceToken', to='devices.device'),
        ),
    ]
