# Generated by Django 4.2.4 on 2023-10-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_alter_token_options_remove_token_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='token',
        ),
    ]
