# Generated by Django 4.2.4 on 2023-10-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_remove_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='devicePassword',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
