# Generated by Django 4.2.4 on 2023-12-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_alter_machine_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
