# Generated by Django 4.2.4 on 2023-12-01 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_alter_machine_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceID',
            field=models.CharField(default=uuid.uuid1, max_length=15, unique=True),
        ),
    ]
