# Generated by Django 4.2.4 on 2023-12-01 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_device_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machineID',
            field=models.CharField(default=uuid.uuid1, max_length=15, unique=True),
        ),
    ]
