# Generated by Django 4.2.4 on 2024-05-03 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('to_number', models.CharField(max_length=15)),
                ('from_number', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('delivery_status', models.TextField(max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='default_sid', max_length=100)),
                ('auth_token', models.CharField(default='default_auth_token', max_length=100)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
    ]
