# Generated by Django 4.2.4 on 2024-05-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsgateway', '0002_alter_sendreport_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsnumber', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sendreport',
            name='from_number',
            field=models.ForeignKey(on_delete=models.SET('Number deleted..'), to='smsgateway.smsnumber'),
        ),
    ]
