# Generated by Django 4.2.4 on 2024-05-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsgateway', '0003_smsnumber_alter_sendreport_from_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='number',
        ),
    ]
