# Generated by Django 4.2.4 on 2024-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsgateway', '0004_remove_setting_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnumber',
            name='smsnumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
