# Generated by Django 4.2.4 on 2024-05-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsgateway', '0005_alter_smsnumber_smsnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendreport',
            name='date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='sendreport',
            name='time',
            field=models.TimeField(editable=False),
        ),
    ]
