# Generated by Django 4.2.4 on 2024-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsgateway', '0007_alter_sendreport_date_alter_sendreport_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendreport',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
