# Generated by Django 4.2.4 on 2024-06-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsgateway', '0008_alter_sendreport_date_alter_sendreport_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
