# Generated by Django 4.2.4 on 2023-08-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_rfid'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.UUIDField(unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('issueTime', models.DateTimeField()),
                ('acknowledgeTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('dateTimeNow', models.DateTimeField(auto_now=True)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('machineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.machine')),
                ('rfidTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.rfid')),
            ],
        ),
        migrations.CreateModel(
            name='LastProblemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.UUIDField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('issueTime', models.DateTimeField()),
                ('acknowledgeTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('dateTimeNow', models.DateTimeField(auto_now_add=True)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('machineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.machine')),
                ('rfidTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.rfid')),
            ],
        ),
    ]
