# Generated by Django 4.2.4 on 2023-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_lastproblemdata_acknowledgetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastproblemdata',
            name='acknowledgeTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
