# Generated by Django 4.2.4 on 2023-09-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_problemdata_eventgroupid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastproblemdata',
            name='UUID',
        ),
        migrations.RemoveField(
            model_name='problemdata',
            name='UUID',
        ),
    ]
