# Generated by Django 4.2.4 on 2023-10-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_rename_hmi_device'),
        ('events', '0016_rename_problemid_problemcode_problemcode'),
        ('data', '0009_remove_lastproblemdata_uuid_remove_problemdata_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='deviceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='eventID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
