# Generated by Django 4.2.4 on 2023-10-15 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rawdata_deviceid_rawdata_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawdata',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
