# Generated by Django 4.2.4 on 2023-10-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_rawdata_date_rawdata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
