# Generated by Django 4.2.4 on 2023-10-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_rename_hmi_device'),
        ('data', '0012_alter_rawdata_date_alter_rawdata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastproblemdata',
            name='deviceID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
