# Generated by Django 4.2.4 on 2023-10-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_problemcode_problemtype'),
        ('data', '0015_alter_lastproblemdata_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='eventGroupID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventgroup'),
        ),
    ]
