# Generated by Django 4.2.4 on 2023-12-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_rfid_rfid_alter_unregistereddevice_deviceid'),
        ('data', '0016_rawdata_eventgroupid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='deviceID',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='machineID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.machine'),
        ),
    ]
