# Generated by Django 4.2.4 on 2023-12-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_rfid_rfid_alter_unregistereddevice_deviceid'),
        ('data', '0017_remove_rawdata_deviceid_rawdata_machineid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='deviceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
