# Generated by Django 4.2.4 on 2024-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotification', '0004_alter_notificationauth_noti_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendreport',
            name='delivery_status',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
