# Generated by Django 4.2.4 on 2024-05-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pushnotification', '0006_remove_sendreport_users_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendreport',
            name='users_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_group', to='auth.group'),
        ),
    ]
