# Generated by Django 4.2.4 on 2024-04-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='default_host', max_length=100)),
                ('port', models.IntegerField(default=8080)),
                ('username', models.CharField(default='default_username', max_length=100)),
                ('password', models.CharField(default='default_password', max_length=100)),
                ('checkstatus', models.BooleanField(default=False)),
                ('checkinterval', models.IntegerField(default=60)),
            ],
        ),
    ]
