# Generated by Django 4.2.4 on 2024-06-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('auth', '0013_alter_user_email'),
        ('emailtracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
