# Generated by Django 4.2.4 on 2024-05-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='parameter_filter_list',
            field=models.ManyToManyField(related_name='parameter_filter_lists', to='emailtracking.parameterfilter'),
        ),
    ]
