# Generated by Django 4.2.4 on 2024-05-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0002_alter_trigger_parameter_filter_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
