# Generated by Django 4.2.4 on 2024-04-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailTracking', '0002_searchparameter_inbox_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='auth_token',
            field=models.CharField(default='default_auth_token', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='settings',
            name='sid',
            field=models.CharField(default='default_sid', max_length=100),
        ),
    ]
