# Generated by Django 4.2.4 on 2024-06-05 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailtracking', '0002_alter_parameter_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='users_to_send',
            field=models.ManyToManyField(related_name='trigger_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
