# Generated by Django 4.2.4 on 2024-05-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0003_rename_settings_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='sid',
        ),
    ]
