# Generated by Django 4.2.4 on 2024-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0003_trigger_users_to_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterfilter',
            name='trigger_fields',
        ),
        migrations.AddField(
            model_name='trigger',
            name='parameter_filter_list',
            field=models.ManyToManyField(related_name='parameter_filter_lists', to='emailtracking.parameterfilter'),
        ),
    ]
