# Generated by Django 4.2.4 on 2024-04-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailTracking', '0004_remove_searchparameter_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchparameter',
            name='country_code',
        ),
    ]
