# Generated by Django 4.2.4 on 2024-06-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0004_remove_parameterfilter_trigger_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_ids', to='emailtracking.setting')),
            ],
        ),
    ]
