# Generated by Django 4.2.4 on 2024-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0004_remove_setting_auth_token_remove_setting_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'field', 'verbose_name_plural': 'fields'},
        ),
        migrations.AlterField(
            model_name='parameter',
            name='alias',
            field=models.CharField(max_length=30),
        ),
    ]
