# Generated by Django 4.2.4 on 2024-05-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0005_alter_parameter_options_alter_parameter_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='trigger_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_field', to='emailtracking.parameter'),
        ),
    ]
