# Generated by Django 4.2.4 on 2024-04-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmailTracking', '0005_remove_searchparameter_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user_list', models.ManyToManyField(related_name='groupemail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
