# Generated by Django 4.2.4 on 2024-06-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('emailtracking', '0006_alter_report_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='group_to_send',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_group', to='auth.group'),
        ),
    ]
