# Generated by Django 4.2.4 on 2024-05-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0006_alter_trigger_trigger_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('active_trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_trigger', to='emailtracking.trigger')),
            ],
        ),
    ]
