# Generated by Django 4.2.4 on 2024-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0007_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterfilter',
            name='operator',
            field=models.CharField(choices=[('greater than or equal', 'Greater than or equal'), ('greater than', 'Greater than'), ('less than or equal', 'Less than or equal'), ('less than', 'Less than'), ('equals', 'Equals'), ('not equals', 'Not Equals'), ('is exist', 'Is Exist')], max_length=25),
        ),
    ]
