# Generated by Django 4.2.4 on 2024-06-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0008_emailid_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailid',
            name='setting',
        ),
    ]
