# Generated by Django 4.2.4 on 2024-06-20 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailtracking', '0009_remove_emailid_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('users_to_send', models.ManyToManyField(related_name='departments_to_send', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='trigger_field',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
