# Generated by Django 4.2.4 on 2024-06-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0010_department_remove_trigger_trigger_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='alias',
            new_name='dep_alias',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dep',
        ),
    ]
