# Generated by Django 4.2.4 on 2024-05-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0011_trigger_actual_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='actual_value',
        ),
        migrations.AddField(
            model_name='report',
            name='actual_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
