# Generated by Django 4.2.4 on 2024-06-20 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailtracking', '0011_rename_alias_department_dep_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='active_trigger',
        ),
        migrations.RemoveField(
            model_name='report',
            name='actual_value',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ticket',
        ),
        migrations.AddField(
            model_name='report',
            name='dep_words',
            field=models.CharField(default='Default Dep Words', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.TextField(default='Default message'),
        ),
        migrations.AddField(
            model_name='report',
            name='users_to_send',
            field=models.ManyToManyField(related_name='report', to=settings.AUTH_USER_MODEL),
        ),
    ]
