# Generated by Django 4.2.4 on 2024-05-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0012_remove_trigger_actual_value_report_actual_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emailtracking.ticket'),
        ),
    ]
