# Generated by Django 4.2.4 on 2024-06-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0013_remove_ticket_log_remove_ticket_required_json_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterFilter',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='users_to_send',
            new_name='send_to_user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
