# Generated by Django 4.2.4 on 2024-06-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0014_delete_parameterfilter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='dep_words',
            new_name='Department',
        ),
    ]
