# Generated by Django 4.2.4 on 2024-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0015_alter_parameter_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='groups',
            field=models.ManyToManyField(blank=True, to='emailtracking.parameter'),
        ),
    ]
