# Generated by Django 4.2.4 on 2024-06-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0016_department_date_department_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='time',
        ),
    ]
