# Generated by Django 4.2.4 on 2024-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0017_remove_department_date_remove_department_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_alias',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('department', 'dep_alias'), name='unique_department_dep_alias'),
        ),
    ]
