# Generated by Django 4.2.4 on 2024-06-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracking', '0017_alter_parameter_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterfilter',
            name='logical_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=3),
        ),
    ]
