# Generated by Django 4.2.4 on 2024-05-09 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_user_expiry_time', models.IntegerField(default=86400)),
                ('OTP_resend_interval', models.IntegerField(default=20)),
                ('OTP_valid_time', models.IntegerField(default=600)),
                ('OTP_call_count', models.IntegerField(default=5)),
                ('OTP_wrong_count', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='UnauthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('createdatetime', models.DateTimeField(auto_now_add=True)),
                ('otp', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('otp_called', models.IntegerField(default=0)),
                ('designation', models.CharField(max_length=15, null=True)),
                ('is_existing_user', models.BooleanField(default=False)),
                ('verification_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=15, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('auth_state', models.IntegerField(default=0)),
                ('expiry_time', models.IntegerField(default=86400)),
                ('extUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraUserDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
