# Generated by Django 4.2.4 on 2024-05-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
