# Generated by Django 4.2.4 on 2024-05-11 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Userauth', '0003_alter_userdetail_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='extUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
