# Generated by Django 4.2.4 on 2024-05-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0004_alter_userdetail_extuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthuser',
            name='designation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='unauthuser',
            name='session_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='unauthuser',
            name='verification_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
