# Generated by Django 4.2.4 on 2024-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0005_alter_unauthuser_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='unAuth_user_expiry_time',
            field=models.IntegerField(default=900),
        ),
    ]
