# Generated by Django 4.2.4 on 2024-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0007_alter_unauthuser_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unauthuser',
            name='otp_wrong_count',
            field=models.IntegerField(default=0),
        ),
    ]
