# Generated by Django 4.2.4 on 2024-06-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0009_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthuser',
            name='otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
